events {
    worker_connections 1024;
}

http {

    # Grupo de servidores que recibirán las solicitudes.
    # NGINX utiliza Round Robin por defecto.
    upstream portal_backend {

        server app1:3000 max_fails=1 fail_timeout=10s;
        server app2:3000 max_fails=1 fail_timeout=10s;

    }


    server {

        listen 80;

        server_name _;


        # Encabezados enviados hacia las aplicaciones.
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;


        # Si una instancia presenta un error de conexión,
        # intentar utilizar otra instancia disponible.
        proxy_next_upstream error timeout http_502 http_503 http_504;


        # Permite comprobar que la respuesta pasó por NGINX.
        add_header X-Proxy-By "NGINX" always;


        # Portal principal
        location / {

            proxy_pass http://portal_backend;

        }


        # Ruta explícita para noticias
        location /noticias/ {

            proxy_pass http://portal_backend;

        }


        # Endpoint de estado
        location = /health {

            proxy_pass http://portal_backend;

        }

    }

}